plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 55

Metrics/BlockLength:
  Max: 70

Metrics/AbcSize:
  Max: 65

Metrics/ParameterLists:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Rails/RedundantActiveRecordAllMethod:
  Enabled: false

Rails/WhereRange:
  Enabled: false