name: CI

on:
  push:
    branches: [ main, database-setup, authentication-feature, cart-checkout-feature ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.9'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: bundle exec rubocop app/

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.9'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
        env:
          RAILS_ENV: test
          SECRET_KEY_BASE: testkeyforcionsecretbase123456789

      - name: Check app boots
        run: bundle exec rails runner "puts 'App boots successfully'"
        env:
          RAILS_ENV: test
          SECRET_KEY_BASE: testkeyforcionsecretbase123456789